### ISSUE TITLE
Not able to run the sample tests on ubuntu

### ISSUE THREAD

**Issue by amarnathk1547** [WillBrock/webdriverio-setup#1]
Hi @WillBrock,
I have been struggling to run the tests with v5 on windows from past weeks. Hence switched to linux machine today. Came across this repo today morning and trying to run the sample tests. still no luck.. Please check the log files attached and let me if something can be done.
Thanks 
[wdio.log](https://github.com/WillBrock/webdriverio-setup/files/2379490/wdio.log)
[wdio-0-0.log](https://github.com/WillBrock/webdriverio-setup/files/2379491/wdio-0-0.log)
[wdio-0-1.log](https://github.com/WillBrock/webdriverio-setup/files/2379492/wdio-0-1.log)
[wdio-0-2.log](https://github.com/WillBrock/webdriverio-setup/files/2379493/wdio-0-2.log)
[wdio-0-3.log](https://github.com/WillBrock/webdriverio-setup/files/2379494/wdio-0-3.log)
[wdio-0-4.log](https://github.com/WillBrock/webdriverio-setup/files/2379495/wdio-0-4.log)

**Comment by WillBrock** [comment]
Are you using npm, what version of that are you on? You'll need to be on version 6 or higher of npm. I think that might be the problem.

`npm -v`

**Comment by WillBrock** [comment]
@amarnathk1547 Were you able to get the tests running? I'm going to close this for now but re-open if you need to.
